backend:
  name: github
  repo: safag05/rsl
  branch: main
  publish_mode: editorial_workflow

media_folder: "images"
public_folder: "images"

collections:
  - name: "data_files"       # Parent collection name
    label: "Data Files"      # What shows up in the CMS sidebar
    files:                   # MUST be the plural 'files'
      
      - name: "teams"
        label: "Teams"
        file: "data/teams.json"
        fields:
          - label: "Teams"
            name: "teams"
            widget: "list"
            fields:
              - { label: "Team Name", name: "name", widget: "string" }

      - name: "fixtures"
        label: "Fixtures"
        file: "data/fixtures.json"
        fields:
          - label: "Weeks"
            name: "weeks"
            widget: "list"
            fields:
              - { label: "Week Name", name: "week", widget: "string" }
              - label: "Games"
                name: "games"
                widget: "list"
                fields:
                  - { label: "Date & Time", name: "date", widget: "datetime", required: false, format: "LLL" }
                  - { label: "Home Team", name: "home", widget: "string" }
                  - { label: "Home Score", name: "homeScore", widget: "number", value_type: "int", default: 0 }
                  - { label: "Away Score", name: "awayScore", widget: "number", value_type: "int", default: 0 }
                  - { label: "Away Team", name: "away", widget: "string" }