backend:
  name: github
  repo: safag05/rsl
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "data_files"
    label: "Data Files"
    files:
      
      - name: "teams"
        label: "Teams"
        file: "data/teams.json"
        fields:
          - label: "Teams"
            name: "teams"
            widget: "list"
            fields:
              - { label: "Team Name", name: "name", widget: "string" }

      - name: "fixtures"
        label: "Fixtures"
        file: "data/fixtures.json"
        fields:
          - label: "Weeks"
            name: "weeks"
            widget: "list"
            fields:
              - { label: "Week Name", name: "week", widget: "string", hint: "e.g. Week 1" }
              - label: "Days"
                name: "days"
                widget: "list"
                fields:
                  - { label: "Date Header", name: "dateHeader", widget: "string", hint: "e.g. Tuesday - 10/17/2023" }
                  - label: "Games"
                    name: "games"
                    widget: "list"
                    fields:
                      - label: "Home Team"
                        name: "home"
                        widget: "relation"
                        collection: "data_files"
                        file: "teams"
                        search_fields: ["teams.name"]
                        display_fields: ["teams.name"]
                        value_field: "teams.name"
                      - { label: "Home Score", name: "homeScore", widget: "string", default: "TBD" }
                      - { label: "Away Score", name: "awayScore", widget: "string", default: "TBD" }
                      - label: "Away Team"
                        name: "away"
                        widget: "relation"
                        collection: "data_files"
                        file: "teams"
                        search_fields: ["teams.name"]
                        display_fields: ["teams.name"]
                        value_field: "teams.name"