backend:
  name: github
  repo: safag05/rsl
  branch: main
  publish_mode: editorial_workflow

media_folder: "images"
public_folder: "/images"

collections:

  - name: "teams"
    label: "Teams"
    file: "data/teams.json"
    fields:
      - label: "Teams"
        name: "teams"
        widget: "list"
        fields:
          - { label: "Team Name", name: "name", widget: "string" }

  - name: "fixtures"
    label: "Fixtures"
    file: "data/fixtures.json"
    fields:
      - label: "Weeks"
        name: "weeks"
        widget: "list"
        fields:
          - { label: "Week", name: "week", widget: "string" }
          - label: "Games"
            name: "games"
            widget: "list"
            fields:
              - { label: "Home Team", name: "home", widget: "string" }
              - { label: "Home Score", name: "homeScore", widget: "number" }
              - { label: "Away Score", name: "awayScore", widget: "number" }
              - { label: "Away Team", name: "away", widget: "string" }